In [2]:
import torch
from torch import nn
import numpy as np

In [43]:
rnn = nn.RNN(3, 2, bias=False, batch_first=True)

In [65]:
print(rnn.weight_ih_l0)
print(rnn.weight_hh_l0)

Parameter containing:
tensor([[-0.1553,  0.4239,  0.3296],
        [ 0.3714, -0.5253, -0.3836]], requires_grad=True)
Parameter containing:
tensor([[ 0.0805,  0.1363],
        [-0.3552,  0.5272]], requires_grad=True)


In [59]:
x = torch.randn(5, 3, 3)

h = torch.randn(1,5,2)

In [74]:
h = torch.zeros((1,5,2))

In [75]:
print(h)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])


In [76]:
output, hn = rnn(x, h)

In [77]:
x

tensor([[[-0.3569, -1.5037, -1.8602],
         [-0.2346, -0.0264, -0.2283],
         [-0.6484,  0.5830,  0.5309]],

        [[-1.9576, -1.8198, -1.3264],
         [-0.0254,  2.0516,  0.8738],
         [-0.3639, -0.6940,  0.7836]],

        [[-0.4094, -0.4804,  1.1435],
         [-0.4696, -0.1970,  1.3389],
         [ 0.6671,  0.1869, -0.6012]],

        [[ 1.3367,  0.0405,  2.3852],
         [ 1.8146,  0.8041, -0.1837],
         [ 0.3763, -0.3636, -1.1467]],

        [[ 0.4333,  1.3355,  0.6118],
         [ 0.2881, -1.0250,  0.0670],
         [-0.5394,  0.9531,  0.8956]]])

In [78]:
output, hn

(tensor([[[-0.8322,  0.8789],
          [ 0.0028,  0.6488],
          [ 0.5452, -0.3882]],
 
         [[-0.7186,  0.6279],
          [ 0.8304, -0.6838],
          [-0.0058, -0.6209]],
 
         [[ 0.2326, -0.3260],
          [ 0.3843, -0.6853],
          [-0.2776, -0.1170]],
 
         [[ 0.5341, -0.4135],
          [-0.0149, -0.0855],
          [-0.5395,  0.6236]],
 
         [[ 0.6047, -0.6500],
          [-0.4599,  0.0622],
          [ 0.6378, -0.6902]]], grad_fn=<TransposeBackward1>),
 tensor([[[ 0.5452, -0.3882],
          [-0.0058, -0.6209],
          [-0.2776, -0.1170],
          [-0.5395,  0.6236],
          [ 0.6378, -0.6902]]], grad_fn=<StackBackward>))

In [30]:
m = nn.Linear(3, 4, bias=False)

In [31]:
inputt = torch.randn(5, 3)

In [36]:
print(m.weight)
print(inputt)
print(m(inputt))

Parameter containing:
tensor([[-0.0749,  0.0515, -0.4355],
        [ 0.1589,  0.1624,  0.3082],
        [-0.5652,  0.3952, -0.2641],
        [ 0.5214, -0.4879,  0.0238]], requires_grad=True)
tensor([[-0.0170, -0.2723, -0.7124],
        [-1.4101,  0.9867,  0.9214],
        [ 0.2109,  0.7999, -0.4678],
        [-0.7239, -0.0634,  0.0549],
        [ 1.3760,  0.9072, -0.2153]])
tensor([[ 0.2975, -0.2665,  0.0901,  0.1070],
        [-0.2447,  0.2200,  0.9435, -1.1947],
        [ 0.2291,  0.0193,  0.3205, -0.2915],
        [ 0.0271, -0.1084,  0.3696, -0.3452],
        [ 0.0374,  0.2997, -0.3622,  0.2697]], grad_fn=<MmBackward>)


In [98]:
x = np.array([[1,2],[2,3], [1,1]])
h = np.array([[1,0],[2,3]])

print(x)
print(h)
ein = np.einsum('bh,hk->bk', x, h)


[[1 2]
 [2 3]
 [1 1]]
[[1 0]
 [2 3]]


array([[5, 6],
       [8, 9],
       [3, 3]])

10
9
8
7
6
5
4
3
2
1
