In [1]:
import numpy as np

In [13]:
class DenseLayer(object):
    
    def __init__(self, input_dim, output_dim, use_bias=True):
        sq = np.sqrt(1. / input_dim)
        print(sq)
        self.use_bias = use_bias
        self.weights = np.random.uniform(-sq, sq, (output_dim, input_dim))
        if use_bias == True:
            self.bias = np.random.uniform(-sq, sq, output_dim)
        else:
            self.bias = np.zeros((output_dim))
        
    def forward(self, X_in):
        return np.tensordot(X_in, self.weights.T, axes=((-1), (0))) + self.bias
        
    def backward(self, dEdY, X_in):
        # dEdW = dEdY * dYdW = dEdY * X
        # dEdb = dEdY * dYdb = dEdY
        # dEdX = dEdY * dYdX = dEdY * W
        axis = tuple(range(len(X.shape) - 1))
        dEdW = np.tensordot(dEdY,X_in, axes=((axis), (axis)))
        dEdB = np.sum(dEdY, axis=(axis))
        dEdX = np.tensordot(dEdY, self.weights, axes=(-1, 0))
        
        return dEdX, dEdW, dEdB
    
    def refresh(self, dEdW, dEdB, learning_rate):
        self.weights = self.weights - learning_rate * dEdW
        if self.use_bias == True:
            self.bias = self.bias - learning_rate * dEdB

In [23]:
dense = DenseLayer(3, 1, True)
X = np.array([[0.2, 0.5, 0.3],
[0.2, 0.4, 0.4],
[0.3, 0.1, 0.6],
[0.2, 0.3, 0.5],
[0.5, 0.3, 0.2]])
Y = np.array([[1.], [1.], [1.], [1.], [1.]])

num_iter = 1

for i in range(num_iter):
    Y_c= dense.forward(X)
    dEdY = Y - Y_c
    _, dEdW, dEdB = dense.backward(dEdY, X)
    dense.refresh(dEdW, dEdB, 0.1)

0.5773502691896257
[[[ 0.42926524 -0.36835554  0.47853077]
  [ 0.39149863 -0.33594775  0.4364298 ]
  [ 0.2803958  -0.24060962  0.31257602]
  [ 0.35373203 -0.30353996  0.39432883]
  [ 0.36032297 -0.30919569  0.40167619]]

 [[ 0.42926524 -0.36835554  0.47853077]
  [ 0.39149863 -0.33594775  0.4364298 ]
  [ 0.2803958  -0.24060962  0.31257602]
  [ 0.35373203 -0.30353996  0.39432883]
  [ 0.36032297 -0.30919569  0.40167619]]]


In [39]:
dense = DenseLayer(5,1,True)
X = np.array([[[-0.8807276 ,  0.35987167,  0.02073506, -0.9615799 ,
          0.50550362],
        [-0.93750772,  0.46892908,  0.65712107, -0.92156692,
          0.81547692],
        [-0.94841669,  0.35337583,  0.13251452, -0.92171502,
          0.96708332]],

       [[-0.98389102,  0.55071545,  0.50947363, -0.99544429,
          0.94198477],
        [-0.88292272,  0.46245851, -0.09000733, -0.72606425,
          0.81062736],
        [-0.58283391, -0.40435749,  0.48705154, -0.8502781 ,
          0.20791288]]])

Y = np.array([[[1],[1],[1]],[[1],[1],[1]]])

num_iter = 1
l = []
for i in range(num_iter):
    Y_c= dense.forward(X)
    dEdY = Y - Y_c
    dEdX, dEdW, dEdB = dense.backward(dEdY, X)
    l = dEdX

l

0.4472135954999579


array([[[ 0.34545989,  0.07336296, -0.16346513, -0.06904482,
          0.0458759 ],
        [ 0.37271336,  0.07915059, -0.17636096, -0.07449179,
          0.04949507],
        [ 0.35166208,  0.07468007, -0.16639989, -0.07028441,
          0.04669953]],

       [[ 0.36616935,  0.07776088, -0.17326446, -0.07318388,
          0.04862605],
        [ 0.33954613,  0.07210709, -0.16066685, -0.06786287,
          0.04509058],
        [ 0.35872758,  0.07618053, -0.16974315, -0.07169654,
          0.04763781]]])