In [36]:
import numpy as np

X_in = np.array([[[1,2,1,3],[2,2,3,1],[0,2,3,1]],[[1,3,4,3],[1,2,1,1],[1,0,1,2]]])
print(X_in.shape)
#batch size 2
#timestep 3
#dim 4

(2, 3, 4)


In [35]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [38]:
class CrossEntropyLoss(object):
    
    def forward(self, Y, o):
        #prvo za jedan primjer
        #ima li svaki podatak iz batcha svoj loss pa se zbraja, ili ce rezultat biti vektor velicina batch_size?
        loss = 0.
        self.Y_pred = softmax(o)
        for i in range (Y.shape[0]):
            loss+=(-Y * np.log(Y_pred)).sum()
            
        return loss
    
    def backward(self,Y):
        return self.Y_pred - Y

In [39]:
o = np.array([[[2.21,0.12,0.78],[0.12,0.80,0.08]],[[0.12,0.11,0.77],[0.06,0.09,0.85]]])
Y_pred = softmax(o)
Y = np.array([[[0.,0.,1.],[0.,1.,0.]],[[0.,0.,1.],[0.,0.,1.]]])

clos = CrossEntropyLoss()

print(clos.forward(Y,Y_pred))
print(clos.backward(Y))

4.333392830695951
[[[ 0.68564883  0.50124999 -0.49875001]
  [ 0.50749719 -0.4156146   0.40925602]]

 [[ 0.31435117  0.49875001 -0.50124999]
  [ 0.49250281  0.4156146  -0.40925602]]]
